local opts = {}
local config_dir = vim.fn.expand(vim.fn.stdpath('config'))
local local_dir = config_dir .. "/local"

opts.autoindent     = true    -- Indent according to previous line.
opts.autoread       = true           -- Load changes automatically,
opts.autowrite      = true          -- write on lose focus.
opts.backspace      = 'indent,eol,start'  -- Make backspace work as you would expect.
opts.backup         = true
opts.backupdir      = local_dir .. "/backup/"
opts.backupext      = '.vim-backup'
opts.breakindentopt = 'shift:2,min:20'
opts.shiftwidth     = 2
opts.clipboard      = 'unnamedplus'
opts.cmdheight      = 2
opts.cmdwinheight   = 5
opts.complete       = '.,w,b,k'       -- C-n completion: Scan buffers, windows and dictionary
opts.completeopt    = 'menu,menuone,noinsert,noselect' -- Set completeopt to have a better completion experience
opts.concealcursor  = 'niv'
opts.conceallevel   = 2
opts.cursorline     = true             -- Find the current line quickly.
opts.diffopt        = 'vertical,iwhite,hiddenoff,filler,internal,algorithm:patience'
opts.directory      = local_dir .. "/swap//"
opts.display        = 'lastline'  -- Show as much as possible of the last line.
opts.equalalways    = false         -- Don't resize windows on split or close
opts.errorbells     = false
opts.expandtab      = true    -- Use spaces instead of tabs.
opts.fcs            = 'eob: '         -- hide ~ tila
opts.fileencoding   = 'utf-8'
opts.fileencodings  = 'utf-8,ucs-bom,gb18030,gbk,gb2312,cp936'
opts.fillchars      = 'eob: ,vert:|'     -- add a bar for vertical splits
opts.foldclose      = 'all'
opts.foldopen       = 'hor,insert,jump,mark,percent,quickfix,search,tag,undo,block'
opts.grepformat     = '%f:%l:%m'
opts.grepprg        = 'rg --vimgrep --smart-case'
opts.helpheight     = 12          -- Minimum help window height
opts.hidden         = true         -- Switch between buffers without having to save first.
opts.history        = 5000
opts.hlsearch       = true       -- Keep matches highlighted.
opts.ignorecase     = true
opts.incsearch      = true      -- Highlight while searching with / or ?.
opts.infercase      = true      -- infer case by first match resutl
opts.isfname        = '@,48-57,/,.,-,_,+,,,#,$,%,~'
opts.laststatus     = 2         -- Always show statusline.
opts.lazyredraw     = false      -- redraw only when necessary.
opts.linebreak      = true           -- set soft wrapping
opts.linespace      = 0            -- No extra spaces between rows
opts.list           = false           -- Show non-printable characters.
opts.magic          = true
opts.mat            = 5                  -- how many tenths of a second to blink
opts.matchpairs     = '(:),{:},[:],<:>'  -- Defines targets of the % motion.
opts.matchtime      = 5            -- Show matching time
opts.mouse          = 'anv'
opts.number         = true
opts.previewheight  = 12       -- Completion preview height
opts.pumheight      = 20           -- Avoid the pop up menu occupying the whole screen
opts.redrawtime     = 1500  -- Maximum time to allow redraw to run before canceling.
opts.relativenumber = false
opts.report         = 2          -- report changed lines?
opts.scrolloff      = 2          -- keep at least N lines on screen when scrolling up/down.
opts.sessionoptions = 'curdir,help,tabpages,winsize'
opts.shada          = "!,%,h,'100,f1,<50,s10240"
opts.shadafile      = local_dir .. "/main.shada"
opts.shiftround     = true    -- Round indent to multiple of 'shiftwidth'
opts.shiftwidth     = 2 -- >> indents by N spaces.
opts.shortmess      = 'filmnrwxsAIqtToOc'
opts.showbreak      = '…'            -- show ellipsis at breaking
opts.showcmd        = true         -- Show already typed keys when more are expected.
opts.showmatch      = true       -- show matching braces
opts.showmode       = true        -- Show current mode in command-line.
opts.signcolumn     = 'yes:1' -- Always show signs column.
opts.smartcase      = true
opts.smarttab       = true    -- tab respects 'tabstop', 'shiftwidth', and 'softtabstop'
opts.softtabstop    = -1       -- Tab key indents default to shiftwidth.
opts.spell          = false
opts.spelllang      = 'en'
opts.spellsuggest   = 'best'
opts.splitbelow     = true
opts.splitright     = true
opts.swapfile       = true
opts.switchbuf      = 'useopen,vsplit' -- Jump to the first open window
opts.synmaxcol      = 2500      -- Only highlight columns to N.
opts.t_8b           = "\\<Esc>[48;2;%lu;%lu;%lum"
opts.t_8f           = "\\<Esc>[38;2;%lu;%lu;%lum"
opts.t_Co           = '256' -- default to 256 Colors.
opts.t_ut           = ''                 -- http://stackoverflow.com/questions/6427650/vim-in-tmux-background-color-changes-when-paging/15095377#15095377
opts.t_vb           = ''
opts.tabstop        = vim.o.shiftwidth
opts.termguicolors  = true
opts.timeout        = true
opts.timeoutlen     = 750  -- time, in milliseconds, to wait for keymap sequence.
opts.title          = true
opts.titlelen       = 95
opts.titlestring    = "%{expand('%:p:~:.')}%(%m%r%w%)"
opts.ttimeout       = true
opts.ttimeoutlen    = 750 -- time, in milliseconds, to wait for key codes ("<Tab>").
opts.ttyfast        = true -- Faster redrawing.
opts.undodir        = local_dir .. "/undo/"
opts.undofile       = true
opts.undofile       = true
opts.updatecount    = 100
opts.updatetime     = 1000 -- time before "write swap" & CursorHold.
opts.viewoptions    = 'folds,cursor,curdir,slash,unix'
opts.visualbell     = true
opts.whichwrap      = 'b,s,<,>,h,l'  -- Allow backspace and cursor keys to cross line boundaries
opts.wildignorecase = true
opts.wildmode       = 'list:longest,full'
opts.winminheight   = 1
opts.winminwidth    = 10 -- minimum size for inactive window.
opts.wrap           = false              -- turn off line wrapping
opts.wrapmargin     = 8        -- wrap lines when coming within n characters from side
opts.wrapscan       = true            -- Searches wrap around end-of-file.
opts.omnifunc       = 'v:lua.vim.lsp.omnifunc'

return opts
